% THIS FUNCTION CALCULATES THE POWERS OF X THAT
% WILL BE USED IN THE DOT PRODUCT AGAINST THE POLYNOMIAL COEFFICIENTS
% INPUTS: 
% 1. INPUT SIGNAL
% 2. N IS EXACTLY WHAT?
function y=x_matrix(x,N)
y=[];

for ii=1:N

y=[y x.^(2*ii-1)];

end